import java.util.Random;
import java.util.Scanner;
import java.util.ArrayList;

public class Games {

    //PRE:  accepts scanner from main
    //POST: asks the user for a 2 digit # & compares the
    //      value to one generated by computer
    //      evaluates whether the user 'won' the lottery
   
    public static void lotteryGame(Scanner input){
        System.out.println("\nWELCOME TO THE LOTTERY!!\n");
        int playing = 1;
        while(playing == 1){
            // Create random number generator and scanner
            Random rand = new Random();
            Scanner scan = new Scanner(System.in);
            // Step 1: Generate a random two-digit lottery number (10 to 99)
            //         && set the 2 digits of lottery number 
            int lotteryNum = (int)(Math.random() * 90) + 10;
            Integer lottery2 = (lotteryNum % 10);
            Integer lottery1 = (lotteryNum / 10);
            // Step 2: Prompt the user to enter a two-digit number
            Integer loop = 0;
            Integer userGuess = 0;
            while (loop == 0){
                System.out.println("Input a number:");
                userGuess = scan.nextInt();

                // Step 3:Ensure it's a valid two-digit number
                if (userGuess > 9 && userGuess < 100){
                    loop = 1;
                }
                else{
                    System.out.println("Number must be between 9 and 100.");
                    continue;
                }
            }

            // Step 4: get the 2 digits of userGuess
            Integer user2 = (userGuess % 10);
            Integer user1 = (userGuess / 10);
            // Step 5: Display lottery number
            System.out.println("Your lottery number is " + lotteryNum);

            // Step 6: Check for types of matches & print results
            // exact match
            if (lotteryNum == userGuess){
                System.out.println("Exact match: You win $10,000!!!");
            }
    
            // Step 7: Check for all digits match (in different order)
            else if (lottery1 == user2 && lottery2 == user1){
                System.out.println("Exact match out of order: You win $3,000!!");
            }
            // Step 8: Check for one digit match
            else if (lottery1 == user1 || lottery2 == user2){
                System.out.println("Single digit match: You win $1,000!");
            }
            // Step 9: No match
            else{
                System.out.println("Sorry, no match.");
            }
            //System.out.println("Continue playing?");
            //String cont = "no";
            //cont = scan.nextLine();
            playing = 0;
            //if (cont.equals("No") || cont.equals("no")){
            //    playing = 0;
            //    break;
            //}
        }
        System.out.println("Thanks for playing!");
    }

    //PRE:  accepts scanner from main
    //POST: while the user chooses to play:
    //      the user will place their bet & roll dice
    //      the game will determine the outcome and update the bet
    //      the user cannot play anymore if they are out of money

    public static void playCraps(Scanner input){
        Random rand = new Random();
        Scanner scan = new Scanner(System.in);
        System.out.println("\nWELCOME TO CRAPS!!\n");
        Double userBet = 0.00;
        Double netWorth = 50.00;
        int playing = 1;
        while (playing == 1){
            System.out.println("Your net worth is: $" + netWorth +
            ". Please enter a valid bet: ");
            userBet = scan.nextDouble();
            int firstRoll = (int)(Math.random() * 6) + 1;
            int secondRoll = (int)(Math.random() * 6) + 1;
            int rollTotal = firstRoll + secondRoll;
            System.out.println("You rolled: " + firstRoll + " + "
            + secondRoll + " = " + rollTotal);
            if (rollTotal == 7 || rollTotal == 11){
                System.out.println("You win!");
                netWorth = netWorth + userBet;
            }
            else if (rollTotal == 2 || rollTotal == 3 || rollTotal == 12){
                System.out.println("You lose!");
                netWorth = netWorth - userBet;
            }
            else{
                int winDecide = 0;
                while (winDecide == 0){
                    int firstPointRoll = (int)(Math.random() * 6) + 1;
                    int secondPointRoll = (int)(Math.random() * 6) + 1;
                    int rollPointTotal = firstPointRoll + secondPointRoll;
                    System.out.println("You rolled: " + firstPointRoll + " + "
                    + secondPointRoll + " = " + rollPointTotal);
                    if (rollPointTotal == 7){
                        winDecide = 1;
                        System.out.println("You lose!");
                        netWorth = netWorth - userBet;
                    }
                    else if (rollPointTotal == rollTotal){
                        winDecide = 1;
                        System.out.println("You win!");
                        netWorth = netWorth + userBet;
                    }
                }
            }
            playing = 0;
            //System.out.println("Continue playing?");
            //String cont = "no";
            //cont = scan.nextLine();
            //if (cont.equals("No") || cont.equals("no")){
            //    playing = 0;
            //    break;
            //}
        }
        System.out.println("Thanks for playing!");
    }

    //PRE: accepts scanner from main
    //POST: while the user chooses to play
    //      the user will place their bet & roll dice
    //      the game will determine the outcome and update the bet
    //      the user cannot play anymore if they are out of money

    public static void playScraps(Scanner input){
        Random rand = new Random();
        Scanner scan = new Scanner(System.in);
        System.out.println("\nWELCOME TO SCRAPS!!\n");
        Double userBet = 0.00;
        Double netWorth = 50.00;
        int playing = 1;
        while (playing == 1){
            System.out.println("Your net worth is: $" + netWorth
                + ". Please enter a valid bet: ");
            userBet = scan.nextDouble();
            int firstRoll = (int)(Math.random() * 8) + 1;
            int secondRoll = (int)(Math.random() * 8) + 1;
            int thirdRoll = (int)(Math.random() * 8) + 1;
            int rollTotal = (firstRoll + secondRoll + thirdRoll);

            System.out.println("Rolled: " + firstRoll + ", "
                + secondRoll + ", " + thirdRoll + " (Total: "
                + rollTotal + ")");

            if ((firstRoll == 7 || secondRoll == 7 || thirdRoll == 7) ||
                (rollTotal == 9 || rollTotal == 10 || rollTotal == 14)){
                System.out.println("You win!");
                netWorth = netWorth + userBet;
            }
            else if ((firstRoll == 1 || secondRoll == 1 || thirdRoll == 1) ||
            (rollTotal == 8 || rollTotal == 20 || rollTotal == 23 || rollTotal == 24)){
                System.out.println("You lose!");
                netWorth = netWorth - userBet;
            }
            else{
                System.out.println("Point is set to " + rollTotal);
                int winDecide = 0;
                while (winDecide == 0){
                    int firstPtRoll = (int)(Math.random() * 8) + 1;
                    int secondPtRoll = (int)(Math.random() * 8) + 1;
                    int thirdPtRoll = (int)(Math.random() * 8) + 1;
                    int rollPtTotal = (firstPtRoll + secondPtRoll + thirdPtRoll);
                    System.out.println("Rolled: " + firstPtRoll + ", "
                        + secondPtRoll + ", " + thirdPtRoll + " (Total: "
                        + rollPtTotal + ")");
                    if ((firstPtRoll == 8 || secondPtRoll == 8 || thirdPtRoll == 8)||
                        rollPtTotal == 15){
                        winDecide = 1;
                        System.out.println("You lose!");
                        netWorth = netWorth - userBet;
                    }
                    else if (rollPtTotal == rollTotal){
                        winDecide = 1;
                        System.out.println("You win!");
                        netWorth = netWorth + userBet;
                    }
                }
            }
            playing = 0;
            //System.out.println("Continue playing?");
            //String cont = "no";
            //cont = scan.nextLine();
            //if (cont.equals("No") || cont.equals("no")){
            //    playing = 0;
            //    break;
            //}
        }
        System.out.println("Thanks for playing!");
    }

    public static void playRPS(Scanner input){
        Random rand = new Random();
        Scanner scan = new Scanner(System.in);
        System.out.println("\nWELCOME TO ROCK, PAPER, SCISSORS!!\n");
        int playing = 1;
        while(playing == 1){
            System.out.println("Enter rock, paper, or scissors: ");
            String userStr = scan.nextLine();
            int userChoice = 8192;
            if(userStr.equals("rock") || userStr.equals("Rock")){
                userChoice = 0;
            }
            else if(userStr.equals("paper") || userStr.equals("Paper")){
                userChoice = 1;
            }
            else if(userStr.equals("scissors") || userStr.equals("Scissors")){
                userChoice = 2;
            }
            else{
                System.out.println("Invalid choice.\n");
                continue;
            }
            int cpuChoice = (int)(Math.random() * 2);
            String cpuStr = "dummy";
            if(cpuChoice == 0){
                cpuStr = "rock";
            }
            else if(cpuChoice == 1){
                cpuStr = "paper";
            }
            else if(cpuChoice == 2){
                cpuStr = "scissors";
            }
            System.out.println("Computer chose " + cpuStr + ".\n");

            if(userChoice == cpuChoice){
                System.out.println("It's a tie!");
            }
            else if((userChoice == 0 && cpuChoice == 1) ||
            (userChoice == 1 && cpuChoice == 2) ||
            (userChoice == 2 && cpuChoice == 0)){
                System.out.println("You lose!");
            }
            else if ((userChoice == 0 && cpuChoice == 2) ||
            (userChoice == 1 && cpuChoice == 0) ||
            (userChoice == 2 && cpuChoice == 1)){
                System.out.println("You win!");
            }
            else{
                System.out.println("Something has gone deeply wrong.");
            }
            System.out.println("Play again?");
            String cont = "no";
            cont = scan.nextLine();
            if (cont.equals("No") || cont.equals("no")){
                playing = 0;
                break;
            }
        }
    }
}